words:
  # Common
  - iban
  - signin
  - signup
  - workareas
  - unattach
  # Uuid lib
  - uuidv
  - uuidv4
  # Hubspot
  - appspot
  - hubspot
  # Netvisor
  - netvisor
  # Netvisor headers
  - Organisation
  - TRANSID
  # Netvisor query parameters
  - paymentstatus
  - lastmodifiedstart
  - netvisorkey
  # Netvisor return object field
  - purchaseinvoicelist
  # Netvisor XML properties
  - vendorbaseinformation
  - vendorcontactdetails
  - organizationid
  - phonenumber
  - contactpersonname
  - contactpersonphonenumber
  - contactpersonemail
  - runbooks
  # Mangopay
  - Mangopay
