words:
  - 'iban'
  - 'netvisor'
  - 'signin'
  - 'signup'
  - 'xlink'
  - 'workareas'
  - 'unattach'
  - 'uuidv'
  - 'uuidv4'
  - 'appspot'
  - 'hubspot'
  - 'purchaseinvoicelist'
  - 'Organisation' # Netvisor header
  - 'TRANSID' # Netvisor header
  - 'paymentstatus' # Netvisor query parameter
  - 'lastmodifiedstart' # Netvisor query parameter
