words:
  # Common
  - 'iban'
  - 'signin'
  - 'signup'
  - 'workareas'
  - 'unattach'
  # Uuid lib
  - 'uuidv'
  - 'uuidv4'
  # Hubspot
  - 'appspot'
  - 'hubspot'
  # Netvisor
  - 'netvisor'
  # Netvisor headers
  - 'Organisation'
  - 'TRANSID'
  # Netvisor query parameters
  - 'paymentstatus'
  - 'lastmodifiedstart'
  # Netvisor return object field
  - 'purchaseinvoicelist'
