words:
  - 'iban'
  - 'netvisor'
  - 'signin'
  - 'signup'
  - 'xlink'
  - 'workareas'
  - 'unattach'
  - 'uuidv'
  - 'uuidv4'
  - 'appspot'
  - 'hubspot'
  - 'purchaseinvoicelist'
  # Netvisor headers
  - 'Organisation'
  - 'TRANSID'
  # Netvisor query parameters
  - 'paymentstatus'
  - 'lastmodifiedstart'
