export enum KycType {
  IDENTITY_PROOF = 'IDENTITY_PROOF',
  REGISTRATION_PROOF = 'REGISTRATION_PROOF',
  ARTICLES_OF_ASSOCIATION = 'ARTICLES_OF_ASSOCIATION',
  SHAREHOLDER_DECLARATION = 'SHAREHOLDER_DECLARATION',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
}
